/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */

  docs: [
    'index',
    /* Scripts */
    {
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts',
        description: 'เอกสารประกอบการใช้งานสำหรับ FiveM Scripts ที่ถูกพัฒนาโดย Azael Dev',
        keywords: ['scripts'],
      },
      items: [
        /* azael_dc-serverlogs */
        {
          type: 'category',
          label: 'azael_dc-serverlogs',
          link: {
            type: 'doc',
            id: 'script/azael_dc-serverlogs/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_dc-serverlogs/config/auth',
                'script/azael_dc-serverlogs/config/server',
                'script/azael_dc-serverlogs/config/client',
                'script/azael_dc-serverlogs/config/shared',
              ],
            },
            {
              type: 'category',
              label: 'exports',
              items: [
                'script/azael_dc-serverlogs/export/server',
                'script/azael_dc-serverlogs/export/client',
              ],
            },
            'script/azael_dc-serverlogs/tutorial',
            {
              type: 'category',
              label: 'รหัสส่งข้อมูล',
              link: {
                type: 'generated-index',
                title: 'ตัวอย่างรหัสส่งข้อมูล',
                description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากรอื่นๆเพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                keywords: ['code-examples'],
                slug: 'script/azael_dc-serverlogs/examples',
              },
              items: [
                {
                  type: 'category',
                  label: 'ESX Framework',
                  link: {
                    type: 'generated-index',
                    title: 'ESX Framework',
                    description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากร ESX Framework เพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                    keywords: ['esx-framework'],
                  },
                  items: [
                    'script/azael_dc-serverlogs/example/esx/es_extended',
                    'script/azael_dc-serverlogs/example/esx/esx_society',
                    'script/azael_dc-serverlogs/example/esx/esx_billing',
                    'script/azael_dc-serverlogs/example/esx/esx_policejob',
                    'script/azael_dc-serverlogs/example/esx/esx_ambulancejob',
                    'script/azael_dc-serverlogs/example/esx/esx_mechanicjob',
                    'script/azael_dc-serverlogs/example/esx/esx_vehicleshop',
                    'script/azael_dc-serverlogs/example/esx/esx_boat',
                    'script/azael_dc-serverlogs/example/esx/esx_garage',
                    'script/azael_dc-serverlogs/example/esx/esx_lscustom',
                    'script/azael_dc-serverlogs/example/esx/esx_accessories',
                    'script/azael_dc-serverlogs/example/esx/esx_clotheshop',
                    'script/azael_dc-serverlogs/example/esx/esx_barbershop',
                    'script/azael_dc-serverlogs/example/esx/esx_weaponshop',
                    'script/azael_dc-serverlogs/example/esx/esx_shops',
                    'script/azael_dc-serverlogs/example/esx/esx_banking',
                    'script/azael_dc-serverlogs/example/esx/esx_drugs',
                  ],
                },
                {
                  type: 'category',
                  label: 'Other Scripts',
                  link: {
                    type: 'generated-index',
                    title: 'Other Scripts',
                    description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากรอื่นๆ (Other Scripts) เพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                    keywords: ['other-scripts'],
                  },
                  items: [
                    'script/azael_dc-serverlogs/example/other/nc_inventory',
                    'script/azael_dc-serverlogs/example/other/nc_vault',
                    'script/azael_dc-serverlogs/example/other/nc_booth',
                    'script/azael_dc-serverlogs/example/other/nc_stealjobs',
                    'script/azael_dc-serverlogs/example/other/nc_tradingjobs',
                    'script/azael_dc-serverlogs/example/other/monster_vault',
                    'script/azael_dc-serverlogs/example/other/new_banking',
                    'script/azael_dc-serverlogs/example/other/esx_inventoryhud',
                    'script/azael_dc-serverlogs/example/other/esx_giveallplayers',
                    'script/azael_dc-serverlogs/example/other/esx_givevehicle',
                    'script/azael_dc-serverlogs/example/other/esx_advancedgarage',
                    'script/azael_dc-serverlogs/example/other/esx_jb_eden_garage2',
                    'script/azael_dc-serverlogs/example/other/lls-mechanic',
                    'script/azael_dc-serverlogs/example/other/gcphone',
                  ],
                },
              ],
            },
          ],
        },
        /* azael_db-health&armor */
        {
          type: 'category',
          label: 'azael_db-health&armor',
          link: {
            type: 'doc',
            id: 'script/azael_db-health&armor/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_db-health&armor/config/auth',
                'script/azael_db-health&armor/config/server',
                'script/azael_db-health&armor/config/client',
                'script/azael_db-health&armor/config/shared',
                'script/azael_db-health&armor/config/database',
              ],
            },
            {
              type: 'category',
              label: 'exports',
              items: [
                'script/azael_db-health&armor/export/client',
              ],
            },
          ],
        },
        /* azael_active-identifiers */
        {
          type: 'category',
          label: 'azael_active-identifiers',
          link: {
            type: 'doc',
            id: 'script/azael_active-identifiers/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_active-identifiers/config/auth',
                'script/azael_active-identifiers/config/server',
                'script/azael_active-identifiers/config/shared',
              ],
            },
          ],
        },
      ],
    },
    /* FAQs */
    {
      type: 'category',
      label: 'FAQs',
      link: {
        type: 'generated-index',
        title: 'FAQs',
        description: 'คำถามที่พบบ่อย (FAQs) เกียวกับวิธีแก้ไขปัญหาทรัพยากร FiveM ที่ถูกพัฒนาโดย Azael Dev',
        keywords: ['faqs'],
      },
      items: [
        {
          type: 'category',
          label: 'Scripts',
          items: [
            'faq/script/azael_dc-serverlogs',
            'faq/script/azael_db-health&armor',
          ],
        },
      ],
    },
  ]
};

module.exports = sidebars;
