/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */

  docs: [
    'index',
    /* Scripts */
    {
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts',
        description: 'เอกสารประกอบการใช้งานสำหรับ FiveM Scripts ที่ถูกพัฒนาโดย Azael Dev',
        keywords: ['scripts'],
      },
      items: [
        /* azael_dc-serverlogs */
        {
          type: 'category',
          label: 'azael_dc-serverlogs',
          link: {
            type: 'doc',
            id: 'script/azael_dc-serverlogs/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_dc-serverlogs/config/auth',
                'script/azael_dc-serverlogs/config/server',
                'script/azael_dc-serverlogs/config/client',
                'script/azael_dc-serverlogs/config/shared',
              ],
            },
          ],
        },
        /* azael_db-health&armor */
        {
          type: 'category',
          label: 'azael_db-health&armor',
          link: {
            type: 'doc',
            id: 'script/azael_db-health&armor/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_db-health&armor/config/auth',
                'script/azael_db-health&armor/config/client',
                'script/azael_db-health&armor/config/shared',
                'script/azael_db-health&armor/config/database',
              ],
            },
            {
              type: 'category',
              label: 'exports',
              items: [
                'script/azael_db-health&armor/export/client',
              ],
            },
          ],
        },
        /* azael_active-identifiers */
        {
          type: 'category',
          label: 'azael_active-identifiers',
          link: {
            type: 'doc',
            id: 'script/azael_active-identifiers/index',
          },
          items: [
            {
              type: 'category',
              label: 'config',
              items: [
                'script/azael_active-identifiers/config/auth',
                'script/azael_active-identifiers/config/server',
                'script/azael_active-identifiers/config/shared',
              ],
            },
          ],
        },
      ],
    },
    /* FAQs */
    {
      type: 'category',
      label: 'FAQs',
      link: {
        type: 'generated-index',
        title: 'FAQs',
        description: 'คำถามที่พบบ่อย (FAQs) เกียวกับวิธีแก้ไขปัญหาทรัพยากร FiveM ที่ถูกพัฒนาโดย Azael Dev',
        keywords: ['faqs'],
      },
      items: [
        {
          type: 'category',
          label: 'Scripts',
          items: [
            'faq/script/azael_db-health&armor',
          ],
        },
      ],
    },
  ]
};

module.exports = sidebars;
